Fix min-chained-call-depth rule
croct-tech/coding-standard-js pull request #134
Opened 2022-03-30 20:22 UTC by georgekaran

## Summary

This pull request aims to fix some conflicts between `min-chained-call-depth` and `newline-per-chained-call`.

### Examples 
✅ Good
```ts
Array(10)
    .fill(10)
    .map(foo => foo)
    .slice(5);
```
```ts
Array(10).fill(10);
```

❌ Bad
```ts
Array(10)
     .fill
    .map(foo => foo)
    .slice(5);
```
```ts
Array(10)
    .fill(10);
```

### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-03-30 20:32 UTC, Fryuni approved these changes

2022-03-31 13:04 UTC, marcospassos commented on src/rules/min-chained-call-depth/index.ts
> +            // If the max depth is greater than ignoreChainWithDepth, we can skip.
```suggestion
            // If the max depth is greater than ignoreChainWithDepth, skip.
```

2022-03-31 13:16 UTC, marcospassos commented on src/rules/min-chained-call-depth/index.ts
> +                    ignoreChainWithDepth: {
```suggestion
                    ignoreChainDeeperThan: {
```

2022-03-31 13:20 UTC, marcospassos requested changes

2022-03-31 13:20 UTC, marcospassos commented on src/rules/min-chained-call-depth/index.ts
>              // We only inline the first level of chained calls.
```suggestion
            // Only affect the root level as the total depth is must be known.
```

2022-03-31 13:20 UTC, marcospassos commented on src/rules/min-chained-call-depth/index.ts
> +            // If the max depth is greater than ignoreChainWithDepth, we can skip.
```suggestion
            // If the max depth is greater than ignore threshold, skit
```

2022-03-31 13:20 UTC, marcospassos commented on src/rules/min-chained-call-depth/index.ts
> +            //     In this case the depth is 3, and the default value of ignoreChainWithDepth is 2.
update the name

2022-03-31 13:51 UTC, marcospassos requested changes

2022-03-31 13:51 UTC, marcospassos commented on docs/rules/min-chained-call-depth.md
> +/*eslint min-chained-call-depth: ["error", {"ignoreChainDeeperThan": 1}]*/
```suggestion
/* eslint min-chained-call-depth: ["error", {"ignoreChainDeeperThan": 1}] */
```

2022-03-31 13:51 UTC, marcospassos commented on src/rules/min-chained-call-depth/index.ts
>                  */
```suggestion
                /* eslint-disable-next-line @typescript-eslint/ban-ts-comment --
                 * NewExpression is a possible callee object type
                 */
```

2022-03-31 13:59 UTC, merged