Add jsx-sort-props rule
croct-tech/coding-standard-js pull request #158
Opened 2022-04-10 21:28 UTC by georgekaran

## Summary

By adding the `jsx-sort-props` rule, the props will now be sorted by alphabetical order, and the multiline props will be automatically listed after all the other props.

Before, the following code would be consider valid:
```tsx
<Hello
  classes={{
    greetings: classes.greetings,
  }}
  active
  validate
  name="John"
  tel={5555555}
/>
```

Now, the same version but with `jsx-sort-props`:
```tsx
<Hello
  active
  validate
  name="John"
  tel={5555555}
  classes={{
    greetings: classes.greetings,
  }}
/>
```

### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-04-10 21:52 UTC, marcospassos commented
Is it auto-fixable?

2022-04-10 21:52 UTC, georgekaran commented
> Is it auto-fixable?

Yep

2022-04-11 00:05 UTC, marcospassos approved these changes

2022-04-11 00:08 UTC, marcospassos requested changes
Not sure if enforcing alphabetical order is a good idea. Sometimes it may just not make sense.

2022-04-11 11:37 UTC, georgekaran commented
> Not sure if enforcing alphabetical order is a good idea. Sometimes it may just not make sense.

It's possible to disable this behavior through the `noSortAlphabetically` prop.

2022-04-11 12:32 UTC, merged