Add rule newline-per-chained-call
croct-tech/coding-standard-js pull request #25
Opened 2022-02-11 01:47 UTC by georgekaran

## Summary

Include rule to break lines when functions have more than one chained call.

### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-02-11 11:57 UTC, Fryuni submitted a review, later dismissed

2022-02-14 00:29 UTC, Fryuni commented
Which scenario do the existing rule do not support that required us to implement a custom one?

2022-02-14 11:44 UTC, georgekaran commented
> Which scenario do the existing rule do not support that required us to implement a custom one?

Sorry my bad, I totally forgot to update the description of the PR.
I've added some examples on why we created a custom rule.

2022-02-14 11:48 UTC, marcospassos requested changes

2022-02-14 11:48 UTC, marcospassos commented on src/rules/newline-per-chained-call/index.test.ts
> +        {code: "const a = window['location'].href.match(/(^[^#]*)/)[0];"},
Some examples are using `\n` (which I find better than using multiline strings, btw), while other rules are using multiline strings. Can we stick to a single form?

2022-02-14 11:48 UTC, marcospassos commented on src/rules/newline-per-chained-call/index.test.ts
> +            errors: [
same

2022-02-14 11:48 UTC, marcospassos commented on src/rules/newline-per-chained-call/index.test.ts
> +.d()`,
same

2022-02-14 11:48 UTC, marcospassos commented on src/rules/newline-per-chained-call/index.ts
> +        }
I see no reason for this function. It's used only once.

2022-02-14 11:48 UTC, marcospassos commented on src/rules/newline-per-chained-call/index.ts
> +                validateCallExpressionIgnoreDepth(node);
Better move it to inside the branch. It's more readable since you don't have extra cases.

2022-02-14 11:50 UTC, marcospassos requested changes
Please include docs for the new rule.

2022-02-14 12:03 UTC, marcospassos commented
If we decide to adopt the `\n`, please fix the other rule's style in another PR as it's unrelated to this.

2022-03-08 20:20 UTC, Fryuni approved these changes

2022-03-08 21:44 UTC, merged